2025-01-15 13:52:29,782 - ERROR    ->  3  -  .  -  .   - Failed to find list of lands on Pliego or Anexo.
Traceback (most recent call last):
  File "/home/miguel/CodingProjects/ScrapingFincasHacienda/scrapingFincasHacienda/Hacienda/pliego_url.py", line 28, in get_pliego
    pliego = soup.find("a", href=const.PLIEGO_PATTERN).get("href")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
2025-01-15 13:52:39,093 - ERROR    ->  3  -  .  -  .   - Failed to find list of lands on Pliego or Anexo.
Traceback (most recent call last):
  File "/home/miguel/CodingProjects/ScrapingFincasHacienda/scrapingFincasHacienda/Hacienda/pliego_url.py", line 28, in get_pliego
    pliego = soup.find("a", href=const.PLIEGO_PATTERN).get("href")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
2025-01-15 13:54:48,698 - ERROR    ->  10 -  2  -  1   - Failed to get the reference value and the 'Report PDF' of the land '4226002QD2742E0021IE'
Traceback (most recent call last):
  File "/home/miguel/CodingProjects/ScrapingFincasHacienda/scrapingFincasHacienda/Catastro/report.py", line 92, in get_data
    self.__access_query_value_page()
  File "/home/miguel/CodingProjects/ScrapingFincasHacienda/scrapingFincasHacienda/Catastro/report.py", line 161, in __access_query_value_page
    query_value_button.click()
  File "/home/miguel/CodingProjects/ScrapingFincasHacienda/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/miguel/CodingProjects/ScrapingFincasHacienda/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 402, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miguel/CodingProjects/ScrapingFincasHacienda/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/miguel/CodingProjects/ScrapingFincasHacienda/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: target frame detached
  (failed to check if window was closed: disconnected: Unable to receive message from renderer)
  (Session info: chrome=131.0.6778.264)
Stacktrace:
#0 0x64f4ef6b91fa <unknown>
#1 0x64f4ef1c966d <unknown>
#2 0x64f4ef1b1772 <unknown>
#3 0x64f4ef1af7e6 <unknown>
#4 0x64f4ef1affcf <unknown>
#5 0x64f4ef1bf877 <unknown>
#6 0x64f4ef1d6a45 <unknown>
#7 0x64f4ef25b143 <unknown>
#8 0x64f4ef23c323 <unknown>
#9 0x64f4ef20ade0 <unknown>
#10 0x64f4ef20bdbe <unknown>
#11 0x64f4ef68512b <unknown>
#12 0x64f4ef6890c7 <unknown>
#13 0x64f4ef6726cc <unknown>
#14 0x64f4ef689c47 <unknown>
#15 0x64f4ef65767f <unknown>
#16 0x64f4ef6a8288 <unknown>
#17 0x64f4ef6a8450 <unknown>
#18 0x64f4ef6b8076 <unknown>
#19 0x7a4bcfe9ca94 <unknown>
#20 0x7a4bcff29c3c <unknown>

