2024-08-23 23:35:51,222 - ERROR    ->  16 -  1  -  1   - Failed to get the reference value and the 'Report PDF' of the land '<Catastro.catastro.Catastro (session="e38ee823bcde0d0d1ebfd48e80e6f862")>'
Traceback (most recent call last):
  File "/home/miguel/coding-projects/ScrapingFincasHacienda/scrapingFincasHacienda/Catastro/report.py", line 60, in get_data
    self.__select_date_and_property()
  File "/home/miguel/coding-projects/ScrapingFincasHacienda/scrapingFincasHacienda/Catastro/report.py", line 148, in __select_date_and_property
    ref_catastral_input.send_keys(self.ref)
  File "/home/miguel/coding-projects/ScrapingFincasHacienda/env/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 232, in send_keys
    Command.SEND_KEYS_TO_ELEMENT, {"text": "".join(keys_to_typing(value)), "value": keys_to_typing(value)}
                                                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/miguel/coding-projects/ScrapingFincasHacienda/env/lib/python3.12/site-packages/selenium/webdriver/common/utils.py", line 137, in keys_to_typing
    characters.extend(val)
TypeError: 'Catastro' object is not iterable
2024-08-23 23:40:54,177 - ERROR    ->  16 -  1  -  1   - Failed to get 'cp, province, locality'.
Traceback (most recent call last):
  File "/home/miguel/coding-projects/ScrapingFincasHacienda/scrapingFincasHacienda/Correos/correos.py", line 33, in get_data
    self.__search()
  File "/home/miguel/coding-projects/ScrapingFincasHacienda/scrapingFincasHacienda/Correos/correos.py", line 65, in __search
    self.__close_cookies()
  File "/home/miguel/coding-projects/ScrapingFincasHacienda/scrapingFincasHacienda/Correos/correos.py", line 62, in __close_cookies
    reject_cookies_btn.click()
  File "/home/miguel/coding-projects/ScrapingFincasHacienda/env/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/miguel/coding-projects/ScrapingFincasHacienda/env/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miguel/coding-projects/ScrapingFincasHacienda/env/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/miguel/coding-projects/ScrapingFincasHacienda/env/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=126.0.6478.126)
Stacktrace:
#0 0x5d0ec112fc5a <unknown>
#1 0x5d0ec0e12c71 <unknown>
#2 0x5d0ec0e607ef <unknown>
#3 0x5d0ec0e5415f <unknown>
#4 0x5d0ec0e825c2 <unknown>
#5 0x5d0ec0e53ad9 <unknown>
#6 0x5d0ec0e8278e <unknown>
#7 0x5d0ec0ea1303 <unknown>
#8 0x5d0ec0e82363 <unknown>
#9 0x5d0ec0e52247 <unknown>
#10 0x5d0ec0e52b9e <unknown>
#11 0x5d0ec10f622b <unknown>
#12 0x5d0ec10fa2d1 <unknown>
#13 0x5d0ec10e1ade <unknown>
#14 0x5d0ec10fae32 <unknown>
#15 0x5d0ec10c677f <unknown>
#16 0x5d0ec111f618 <unknown>
#17 0x5d0ec111f7f0 <unknown>
#18 0x5d0ec112ed8c <unknown>
#19 0x7399df6b939d <unknown>
#20 0x7399df73e49c <unknown>

2024-08-23 23:49:28,963 - ERROR    ->  16 -  1  -  2   - Failed to get 'cp, province, locality'.
Traceback (most recent call last):
  File "/home/miguel/coding-projects/ScrapingFincasHacienda/scrapingFincasHacienda/Correos/correos.py", line 33, in get_data
    self.__search()
  File "/home/miguel/coding-projects/ScrapingFincasHacienda/scrapingFincasHacienda/Correos/correos.py", line 66, in __search
    search_input = self.find_element(
                   ^^^^^^^^^^^^^^^^^^
  File "/home/miguel/coding-projects/ScrapingFincasHacienda/env/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miguel/coding-projects/ScrapingFincasHacienda/env/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/miguel/coding-projects/ScrapingFincasHacienda/env/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=126.0.6478.126)
Stacktrace:
#0 0x62ac4483ac5a <unknown>
#1 0x62ac4451de2c <unknown>
#2 0x62ac444f30d4 <unknown>
#3 0x62ac44595a8d <unknown>
#4 0x62ac445abca6 <unknown>
#5 0x62ac4458d363 <unknown>
#6 0x62ac4455d247 <unknown>
#7 0x62ac4455db9e <unknown>
#8 0x62ac4480122b <unknown>
#9 0x62ac448052d1 <unknown>
#10 0x62ac447ecade <unknown>
#11 0x62ac44805e32 <unknown>
#12 0x62ac447d177f <unknown>
#13 0x62ac4482a618 <unknown>
#14 0x62ac4482a7f0 <unknown>
#15 0x62ac44839d8c <unknown>
#16 0x71cadd24839d <unknown>
#17 0x71cadd2cd49c <unknown>

2024-08-23 23:52:06,734 - ERROR    ->  16 -  1  -  2   - Failed to get 'cp, province, locality'.
Traceback (most recent call last):
  File "/home/miguel/coding-projects/ScrapingFincasHacienda/scrapingFincasHacienda/Correos/correos.py", line 33, in get_data
    self.__search()
  File "/home/miguel/coding-projects/ScrapingFincasHacienda/scrapingFincasHacienda/Correos/correos.py", line 65, in __search
    self.__close_cookies()
  File "/home/miguel/coding-projects/ScrapingFincasHacienda/scrapingFincasHacienda/Correos/correos.py", line 62, in __close_cookies
    reject_cookies_btn.click()
  File "/home/miguel/coding-projects/ScrapingFincasHacienda/env/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/miguel/coding-projects/ScrapingFincasHacienda/env/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miguel/coding-projects/ScrapingFincasHacienda/env/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/miguel/coding-projects/ScrapingFincasHacienda/env/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=126.0.6478.126)
Stacktrace:
#0 0x59985de96c5a <unknown>
#1 0x59985db79c71 <unknown>
#2 0x59985dbc77ef <unknown>
#3 0x59985dbbb15f <unknown>
#4 0x59985dbe95c2 <unknown>
#5 0x59985dbbaad9 <unknown>
#6 0x59985dbe978e <unknown>
#7 0x59985dc08303 <unknown>
#8 0x59985dbe9363 <unknown>
#9 0x59985dbb9247 <unknown>
#10 0x59985dbb9b9e <unknown>
#11 0x59985de5d22b <unknown>
#12 0x59985de612d1 <unknown>
#13 0x59985de48ade <unknown>
#14 0x59985de61e32 <unknown>
#15 0x59985de2d77f <unknown>
#16 0x59985de86618 <unknown>
#17 0x59985de867f0 <unknown>
#18 0x59985de95d8c <unknown>
#19 0x7d5613dc339d <unknown>
#20 0x7d5613e4849c <unknown>

